# Generated by Django 5.2.6 on 2025-10-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.BooleanField(default=False)),
                ('human_resources', models.BooleanField(default=False)),
                ('pos', models.BooleanField(default=False)),
                ('accounting', models.BooleanField(default=False)),
                ('authentication', models.BooleanField(default=False)),
                ('authorization', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
    ]
