# Generated by Django 5.2.6 on 2025-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchaseorder_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
